import { Injectable } from '@nestjs/common';
import OpenAI from 'openai';
import { ConfigService } from '@nestjs/config';
import { Env } from '../../env.model';

@Injectable()
export class OpenaiService {
  private openai: OpenAI; // declaro la propiedad openai de tipo OpenAI

  constructor(configService: ConfigService<Env>) {
    const apiKey = configService.get('OPENAI_API_KEY', { infer: true }); // obtengo la clave de la API de OpenAI desde las variables de entorno
    if (!apiKey) {
      throw new Error('OPENAI_API_KEY is not defined in the environment variables.');
    }
    this.openai = new OpenAI({ apiKey }); // inicializo la propiedad openai con la clave de la API
  }

  async generateSummary(content: string) {
    const response = await this.openai.responses.create({
      model: 'gpt-4o-mini',
      instructions: 'You are a helpful assistant that summarizes the content provided. Please provide a concise summary of the following content. You should generate a summary with 255 characters or less.',
      input: content,
    });
    return response.output_text; // devuelvo el texto de salida generado por el modelo
  }

  async generateImage(text: string) {
    const prompt = `Create an image that represents the following text: "${text}"`;
    const response = await this.openai.images.generate({
      model: 'dall-e-3',
      prompt: prompt,
      response_format: 'url', // especifico que quiero recibir la URL de la imagen generada
    });
    if (!response.data || response.data.length === 0) {
      throw new Error('No image generated by the model.');
    }
    return response.data[0].url; // devuelvo la URL de la imagen generada por el modelo
  }
}
